# Generated by Django 5.2.5 on 2025-09-12 12:05

import distributer.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='distributer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eamil', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(blank=True)),
                ('address', models.CharField(max_length=250)),
                ('date_of_bearth', models.DateField(null=True)),
                ('adhar_number', models.CharField(default='1234567890123456', max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Aadhar number must be 16 digits')])),
                ('insurnce_number', models.CharField(max_length=80, null=True)),
                ('insurnce_expiry_date', models.DateField()),
                ('area_of_specialization', models.CharField(max_length=80)),
                ('preferred_sale_area', models.CharField(max_length=120, null=True)),
                ('bank_name', models.CharField(max_length=80)),
                ('account_type', models.CharField(max_length=80)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('bank_account', models.IntegerField(null=True)),
                ('pan_number', models.CharField(max_length=50)),
                ('partner_code', models.CharField(default='1dds567', max_length=100, unique=True)),
                ('bank_imag', models.FileField(upload_to='uploads/', validators=[distributer.models.validate_file_type])),
                ('adhar_card', models.FileField(upload_to='uploads/', validators=[distributer.models.validate_file_type])),
                ('pan_card', models.FileField(upload_to='uploads/', validators=[distributer.models.validate_file_type])),
                ('photo', models.FileField(upload_to='uploads/', validators=[distributer.models.validate_file_type])),
                ('terms_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
