# Generated by Django 5.2.5 on 2025-09-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributer',
            name='partner_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
