# Generated by Django 5.2.5 on 2025-08-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_synckplan_featcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synckplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
