# Generated by Django 5.2.5 on 2025-08-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_synckplan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='synckplan',
            name='domains',
            field=models.CharField(default='as', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synckplan',
            name='planId',
            field=models.CharField(default='asda', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='synckplan',
            name='featcher',
            field=models.TextField(),
        ),
    ]
