# Generated by Django 5.2.5 on 2025-09-02 06:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('manager', 'Manager'), ('retailer', 'Retailer'), ('admin', 'Admin'), ('normal', 'Normal')], max_length=100)),
                ('password', models.CharField(max_length=128, validators=[accounts.models.validate_strong_password])),
                ('permission', models.ManyToManyField(related_name='users', to='accounts.permission')),
            ],
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
        migrations.DeleteModel(
            name='Registerlogin',
        ),
    ]
