# Generated by Django 5.2.5 on 2025-09-02 07:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permission_user_delete_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('manager', 'Manager'), ('retailer', 'Retailer'), ('admin', 'Admin'), ('normal', 'Normal')], max_length=100)),
                ('password', models.CharField(max_length=128, validators=[accounts.models.validate_strong_password])),
                ('permission', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
