# Generated by Django 5.2.5 on 2025-09-03 07:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_registerlogin_groups_registerlogin_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerlogin',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='registerlogin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='registerlogin',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='registerlogin',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='registerlogin',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='registerlogin',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='registerlogin',
            name='password',
            field=models.CharField(max_length=128, validators=[accounts.models.validate_strong_password]),
        ),
        migrations.AlterField(
            model_name='registerlogin',
            name='permission',
            field=models.TextField(),
        ),
    ]
