# Generated by Django 5.2.5 on 2025-09-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_registerlogin_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerlogin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
