# Generated by Django 5.2.5 on 2025-09-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_registerlogin_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerlogin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
