# Generated by Django 5.2.5 on 2025-09-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_registerlogin_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerlogin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='registerlogin',
            name='last_login',
        ),
    ]
