# Generated by Django 5.2.5 on 2025-09-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_registerlogin_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerlogin',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
