# Generated by Django 5.2.5 on 2025-08-25 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('alert', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AdditionalPlan',
            },
        ),
        migrations.CreateModel(
            name='Covrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageBand', models.CharField(choices=[('18-35', '18 to 35 Years'), ('36-45', '36 to 45 Years'), ('46-60', '46 to 60 Years'), ('61-65', '61 to 65 Years'), ('65+', '65 Years above')], max_length=10)),
                ('level', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('additional_planId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addiPlans.additionalplan')),
            ],
            options={
                'db_table': 'Covrage',
            },
        ),
    ]
