# Generated by Django 5.2.5 on 2025-08-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addiPlans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covrage',
            old_name='value',
            new_name='price',
        ),
    ]
